name: Test lint and build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          persist-credentials: false 
          fetch-depth: 0 

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
        cache: false

    - uses: extractions/setup-just@v1

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.57.2
        args: --out-format=colored-line-number -v ./...

    - name: Test
      run: just test-ci

    - name: Go Coverage Badge
      uses: tj-actions/coverage-badge-go@v2
      with:
        filename: coverage.out

    - name: Build
      run: go build -v ./...
